// <auto-generated />
namespace TestingApp.Repo1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class secondone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondone));
        
        string IMigrationMetadata.Id
        {
            get { return "202101251345223_secondone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
